### ISSUE TITLE
Unknown fields in logs

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/jobset#141]
As I am looking at the integration logs, I see the following warning:

```
2023-05-12T19:07:27Z  INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[0].template.metadata.creationTimestamp"
  2023-05-12T19:07:27Z  INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[0].template.spec.template.metadata.creationTimestamp"
  2023-05-12T19:07:27Z  INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[1].template.metadata.creationTimestamp"
  2023-05-12T19:07:27Z  INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[1].template.spec.template.metadata.creationTimestamp"
  S
  ```
  
  I don't think its causing any issue but wanted to bring awareness to this.  Not sure of the solution or if it is necessary to solve it.  It happens also in the logs of the integration tests in the CI.

**Comment by kannon92** [comment]
No, and google wasn't too helpful in figuring out where it was coming from.  I'm still new to writing controllers so not sure where the responsibility of controller-runtime is versus jobset_controller.  

I didn't see any examples of us using this field in the controller.

**Comment by tenzen-y** [comment]
@kannon92 @ahg-g That error is caused by the controller-gen bug: https://github.com/kubernetes-sigs/controller-tools/issues/402. And then, the bug was fixed in controller-gen v0.11.4

**Comment by tenzen-y** [comment]
It seems that we have already used v0.11.4. So, we probably don't face this error.

https://github.com/kubernetes-sigs/jobset/blob/321a9d664acdbdf344df007a9f17f48b355d1913/Makefile#L187
https://github.com/kubernetes-sigs/jobset/blob/321a9d664acdbdf344df007a9f17f48b355d1913/config/components/crd/bases/jobset.x-k8s.io_jobsets.yaml#L2-L7

**Comment by kannon92** [comment]
I see it in these logs on our integration tests (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_jobset/171/pull-jobset-test-integration-main/1664000334931955712/build-log.txt)

**Comment by tenzen-y** [comment]
Which PR?  Maybe it is fixed by rebasing the PR.

**Comment by tenzen-y** [comment]
Actually, we couldn't see the error on the latest PR (#171).

**Comment by vsoch** [comment]
I just hit this locally:

```
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[0].template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[0].template.spec.template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[1].template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[1].template.spec.template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[2].template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[2].template.spec.template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[3].template.metadata.creationTimestamp"
2023-06-06T18:32:26Z    INFO    KubeAPIWarningLogger    unknown field "spec.replicatedJobs[3].template.spec.template.metadata.creationTimestamp"
```
I'm running a size 4 node minikube cluster, and I tried installing from both the main branch and the last release. I produced it on kind too and switched over to see if it was related, seems to appear in both.

In my case, I don't see other errors in the logs, and I can see the spec for my jobset, but there are absolutely no events and nothing created. I'm hoping it's related to this issue (although it might not be, it's hard to tell!) I'm going to debug a little more and I'll open a separate issue if there seems to be something else going on. In the meantime, if anyone has tips for debugging jobsets that don't show up beyond the spec for get/describe (no pods, events, etc) please let me know!

**Comment by danielvegamyhre** [comment]
Just checked and this issue is still occurring. It doesn't seem to affect anything, though. This is strange since during the time since this bug was created, we have bumped the versions of our major dependencies multiple times. I can't prioritize this right now but we can keep the issue open.

/label lifecycle/frozen

**Comment by carreter** [comment]
Running into this myself now, it results in a lot of noise that makes JobSet harder to debug. Will poke around and see if I find anything.

**Comment by carreter** [comment]
Tracked down the logs to being emitted here:

https://github.com/kubernetes-sigs/jobset/blob/5cd8d28cf29fd01e7854b80c41bb677850bae7ce/pkg/controllers/jobset_controller.go#L254-L271

I suspect that the client is updating JobSetSpec fields, not just the JobSetStatus subresource. Investigating more now.

EDIT: I'm losing my mind trying to track down why this is happening, giving up for now

**Comment by carreter** [comment]
I think this might be a bug in `controller-runtime`, as that's where `JobSetReconciler` gets its client from. I can't see any other reason why making a call to the `Status()` subresource would cause the error messages. I'll file a bug over there and reference this issue.

**Comment by tchap** [comment]
Just linking a useful comment from the PR I am going to close: https://github.com/kubernetes-sigs/jobset/pull/944#issuecomment-3127950161

**Comment by tchap** [comment]
Regarding https://github.com/kubernetes-sigs/jobset/pull/944#issuecomment-3127950161, I think that 2) would be a better approach.

There are actually some additional issues right now. When you run `kubectl explain jobset.spec.replicatedJobs.template.metadata`, you can see the following:

```
GROUP:      jobset.x-k8s.io
KIND:       JobSet
VERSION:    v1alpha2

FIELD: metadata <Object>


DESCRIPTION:
    Standard object's metadata of the jobs created from this template.
    More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    
FIELDS:
  annotations   <map[string]string>
    <no description>

  finalizers    <[]string>
    <no description>

  labels        <map[string]string>
    <no description>

  name  <string>
    <no description>

  namespace     <string>
    <no description>
```

Now the issue is, you can realistically only set additional labels and annotations. Finalizers are ignored, name/namespace overwritten. So I don't think this should even be part of the API, it should not be there at all.

So to reflect reality, we should use

```golang
type CustomJobTemplate struct {
    Metadata CustomMetadata  `json:"metadata"`
    Spec     batchv1.JobSpec `json:"spec"`
}

type CustomMetadata struct {
    Labels      map[string]string `json:"labels,omitempty"`
    Annotations map[string]string `json:"annotations,omitempty"`
}
```

This would actually break both the package API and the CRD API. The question is whether any of this really matters. As mentioned by the original comment, there is no promise of package-level compatibility as of now. Regarding CRD, if you set any of the extra fields, it actually points to a bug. You are setting fields that are being ignored. So I am wondering whether we really need to release a new API version for this. Strictly speaking yes, realistically speaking probably no?

Another approach would be to keep the extra fields from `explain` there for now, change the package API, and finish everything right before `v1`. I would rather go the simple way, but yeah, there are some contracts, strictly speaking.

Opinions?

**Comment by tchap** [comment]
@kannon92 I think that we should really do something about this soon and definitely before 1.0. See my last major comment, please. What do you think?

**Comment by kannon92** [comment]
cc @andreyvelich @ahg-g @GiuseppeTT 

We got a report of this internally and there is renewed interest in removing these logs.

It seems that the suggestion is to follow https://github.com/kubernetes-sigs/jobset/issues/141#issuecomment-3135993522 suggestion.

**Comment by ahg-g** [comment]
sounds good, but do we know how to get rid of them?

**Comment by tenzen-y** [comment]
@kannon92 @ahg-g IIUC, this will be resolved since the metadata creationTimestamp field has now the `omitzero` tag.
Are you still observing the warnings?

https://github.com/kubernetes/kubernetes/issues/67610

**Comment by kannon92** [comment]
> [@kannon92](https://github.com/kannon92) [@ahg-g](https://github.com/ahg-g) IIUC, this will be resolved since the metadata creationTimestamp field has now the `omitzero` tag. Are you still observing the warnings?
> 
> [kubernetes/kubernetes#67610](https://github.com/kubernetes/kubernetes/issues/67610)

@tchap would you like to check?

**Comment by tchap** [comment]
The log entry is gone now. However, there is a new spam log entry caused by https://github.com/kubernetes/kubernetes/issues/134040 . There is a pending PR for that already. In any case, this issue can be closed.

**Comment by kannon92** [comment]
> [@kannon92](https://github.com/kannon92) [@ahg-g](https://github.com/ahg-g) IIUC, this will be resolved since the metadata creationTimestamp field has now the `omitzero` tag. Are you still observing the warnings?
> 
> [kubernetes/kubernetes#67610](https://github.com/kubernetes/kubernetes/issues/67610)

Wow! nice detective work.

Sounds like this is fixed in main due to us using 1.34 APIs.

/close
